---
- hosts: webservers
  vars:
    http_port: 80
    max_clients: 200
  remote_user: root
  tasks:
  - name: ensure apache is at the latest version
    yum:
      name: httpd
      state: latest
  - name: write the apache config file
    template:
      src: /srv/httpd.j2
      dest: /etc/httpd.conf
    notify:
    - restart apache
  - name: ensure apache is running
    service:
      name: httpd
      state: started
  handlers:
    - name: restart apache
      service:
        name: httpd
        state: restarted

- nagios:
  action: enable_alerts
  service: httpd
  host: '{{ hostanme }}'

  #Through in a nagios module since I believe you said you were using that. 3. Would be done via autoscaling I would presume but I guess that's a
  #further discussion. Not super fleshed out, but I think it satisfies the requirements. FYI, I didn't create this, but why reinvent the wheel if
  #someone else has already done the work. Working smarter and not harder as they say. 
